In [36]:
import os
import glob
import pandas as pd
import numpy as np 
import datetime 
##os.chdir("/FirstProject")

In [37]:
data = pd.read_csv('covid_concatenated.csv')

In [38]:
### moving CSV file to a df just in case 
df = pd.DataFrame(data)

In [39]:
## New df from the original one to get only the columns that we want 
days_count = pd.DataFrame(data[["CountryName", "StartDate", "EndDate", "PolicyValue"]])

##Adding a new column to the new dataframe with the daydifference between EndDate and StartDate
days_count['DayDiff'] = pd.to_datetime(days_count['EndDate'], format="%Y/%m/%d") - pd.to_datetime(days_count['StartDate'], format="%Y/%m/%d")#.astype(str).astype(int)
days_count

      CountryName   StartDate     EndDate  PolicyValue  DayDiff
0          Brazil  2020-03-13  2020-05-04          1.0  52 days
1          Brazil  2020-05-05  2020-08-23          2.0 110 days
2          Brazil  2020-08-24  2020-08-30          3.0   6 days
3          Brazil  2020-08-31         NaN          2.0      NaT
4           Italy  2020-02-23  2020-03-09          2.0  15 days
5           Italy  2020-03-10  2020-03-19          2.0   9 days
6           Italy  2020-03-20  2020-04-09          3.0  20 days
7           Italy  2020-04-10  2020-05-03          2.0  23 days
8           Italy  2020-05-04  2020-07-26          1.0  83 days
9           Italy  2020-07-27         NaN          0.0      NaT
10      Singapore  2020-04-03  2020-04-07          1.0   4 days
11      Singapore  2020-04-08  2020-06-18          2.0  71 days
12      Singapore  2020-06-19         NaN          1.0      NaT
13   South Africa  2020-03-26  2020-05-31          2.0  66 days
14   South Africa  2020-06-01  2020-07-11          1.0  40 days
15   South Africa  2020-07-12         NaN          2.0      NaT
16  United States  2020-03-15  2020-07-19          2.0 126 days
17  United States  2020-07-20  2020-09-11          1.0  53 days
18  United States  2020-09-12         NaN          1.0      NaT

### The way to get the weighted average of policy value per month is: PolicyValue times number of days policy was active during a specific month, divided by the number of days in the month

## Brazil

In [40]:
#crop = {'Month': ['February', 'March', 'April', 'May', 'June', 'July', 'August', 'September'], 
#        'Days': [29, 31, 30, 31, 30, 31, 31, 30]}
#crop_df = pd.DataFrame(crop, columns=['Month', 'Days'])

##march= pd.to_numeric(days_count[[0:3]])* pd.to_numeric(days_count[[0:4]])/ pd.to_numeric(crop_df[[0:1]])

feb= (0.0*0.0)/29
march= (1.0*31)/31
april= (1.0*30)/30
may1=(1.0*5)
may2=(2.0*26)
may_total= (may1+may2)/31
june=(2.0*30)/30
july=(2.0*31)/31
august1=(2.0*23)
august2=(3.0*7)
august3=(2.0*1)
august_total= (august1+august2+august3)/31
sep=(0.0*0.0)/30

months_brazil = [feb,march, april, may_total, june, july, august_total, sep]

# Had to turn it into a DataFrame because I was running into issues while adding the columng to the next dataframe
month_value = pd.DataFrame(months_brazil)

months= {'CountryName': ['Brazil','Brazil','Brazil','Brazil','Brazil','Brazil','Brazil','Brazil'],
        'Year_Month': ['2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09']}
brazil = pd.DataFrame(months, columns=['CountryName', 'Year_Month'])
brazil['PolicyValue'] = month_value

## Italy

In [41]:
feb_it= (2.0*6)/29
march1_it= (2.0*9)
march2_it= (2.0*9)
march3_it= (3.0*11)
marchtotal_it = (march1_it+march2_it+march3_it)/31
april1_it= (3.0*9)
april2_it= (2.0*21)
apriltotal_it= (april1_it+april2_it)/30
may1_it=(2.0*3)
may2_it=(2.0*28)
maytotal_it= (may1_it+may2_it)/31
june1_it=(1.0*26)
june2_it=(0.0*4)
junetotal_it= (june1_it+june2_it)/30
july_it=(0.0*31)/31
august_it=(0.0*31)/31
sep_it=(0.0*0.0)/30

months_italy = [feb_it, marchtotal_it, apriltotal_it, maytotal_it, junetotal_it, july_it, august_it, sep_it]
month_italy_value = pd.DataFrame(months_italy)

months_it= {'CountryName': ['Italy','Italy','Italy','Italy','Italy','Italy','Italy','Italy'],
        'Year_Month': ['2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09']}
italy = pd.DataFrame(months_it, columns=['CountryName', 'Year_Month'])
italy['PolicyValue'] = month_italy_value

## Singapore

In [42]:
feb_sing= (0.0*29)/29
march_sing= (0.0*31)/31
april_sing= (1.0*4)
april_sing2= (2.0*22)
apriltotal_sing= (april_sing+april_sing2)/30
may_sing= (2.0*31)/31
jun_sing= (2.0*18)
jun_sing2= (1.0*12)
juntotal_sing= (jun_sing+jun_sing2)/30
jul_sing= (0.0*31)/31
aug_sing= (0.0*31)/31
sep_sing= (0.0*30)/30

months_singapore = [feb_sing, march_sing, apriltotal_sing, may_sing, juntotal_sing, jul_sing, aug_sing, sep_sing]
month_sing_value = pd.DataFrame(months_singapore)

months_sing= {'CountryName': ['Singapore','Singapore','Singapore','Singapore','Singapore','Singapore','Singapore','Singapore'],
        'Year_Month': ['2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09']}
singapore = pd.DataFrame(months_sing, columns=['CountryName', 'Year_Month'])
singapore['PolicyValue'] = month_sing_value

## South Africa

In [43]:
feb_sa= (0.0*29)/29
march_sa= (2.0*5)/31
april_sa=(2.0*30)/30
may_sa= (2.0*31)/31
jun_sa= (1.0*30)/30
jul_sa= (1.0*11)
jul_sa2= (2.0*19)
jultotal_sa= (jul_sa+jul_sa2)/31
aug_sa= (0.0*31)/31
sep_sa= (0.0*30)/30

months_safa = [feb_sa, march_sa, april_sa, may_sa, jun_sa, jultotal_sa, aug_sa, sep_sa]
month_safa_value = pd.DataFrame(months_safa)

months_sa= {'CountryName': ['South Africa','South Africa','South Africa','South Africa','South Africa','South Africa','South Africa','South Africa'],
        'Year_Month': ['2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09']}
safa = pd.DataFrame(months_sa, columns=['CountryName', 'Year_Month'])
safa['PolicyValue'] = month_safa_value

## USA

In [44]:
feb_usa= (0.0*29)/29
march_usa= (2.0*16)/31
april_usa= (2.0*30)/30
may_usa= (2.0*31)/31
jun_usa= (2.0*30)/30
jul_usa= (2.0*19)
jul_usa2= (1.0*12)
jultotal_usa= (jul_usa+jul_usa2)/31
aug_usa= (1.0*31)/31
sep_usa= (1.0*11)
sep_usa2= (1.0*19)
septotal_usa= (sep_usa+sep_usa2)/30

months_usa = [feb_usa, march_usa, april_usa, may_usa, jun_usa, jultotal_usa, aug_usa, septotal_usa]
month_usa_value = pd.DataFrame(months_usa)

months_us= {'CountryName': ['USA','USA','USA','USA','USA','USA','USA','USA'],
        'Year_Month': ['2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09']}
usa = pd.DataFrame(months_us, columns=['CountryName', 'Year_Month'])
usa['PolicyValue'] = month_usa_value

### Concat countries, turn it into a new dataframe, and reset index

In [45]:
#Put all dataframes together (concat) and turn them into a new dataframe
prep = pd.concat([brazil, italy, singapore, safa, usa])
prep_df = pd.DataFrame(prep)

#Resent the Index
prep_df.index = range(len(prep_df))
prep_df

     CountryName Year_Month  PolicyValue
0         Brazil    2020-02     0.000000
1         Brazil    2020-03     1.000000
2         Brazil    2020-04     1.000000
3         Brazil    2020-05     1.838710
4         Brazil    2020-06     2.000000
5         Brazil    2020-07     2.000000
6         Brazil    2020-08     2.225806
7         Brazil    2020-09     0.000000
8          Italy    2020-02     0.413793
9          Italy    2020-03     2.225806
10         Italy    2020-04     2.300000
11         Italy    2020-05     2.000000
12         Italy    2020-06     0.866667
13         Italy    2020-07     0.000000
14         Italy    2020-08     0.000000
15         Italy    2020-09     0.000000
16     Singapore    2020-02     0.000000
17     Singapore    2020-03     0.000000
18     Singapore    2020-04     1.600000
19     Singapore    2020-05     2.000000
20     Singapore    2020-06     1.600000
21     Singapore    2020-07     0.000000
22     Singapore    2020-08     0.000000
23     Singapore    2020-09     0.000000
24  South Africa    2020-02     0.000000
25  South Africa    2020-03     0.322581
26  South Africa    2020-04     2.000000
27  South Africa    2020-05     2.000000
28  South Africa    2020-06     1.000000
29  South Africa    2020-07     1.580645
30  South Africa    2020-08     0.000000
31  South Africa    2020-09     0.000000
32           USA    2020-02     0.000000
33           USA    2020-03     1.032258
34           USA    2020-04     2.000000
35           USA    2020-05     2.000000
36           USA    2020-06     2.000000
37           USA    2020-07     1.612903
38           USA    2020-08     1.000000
39           USA    2020-09     1.000000

In [47]:
#convert the normalised dataframe to a csv file 
prep_df.to_csv('normalised_oxford.csv', sep=',')